local pack_opts = { confirm = false, load = true }

vim.g.barbar_auto_setup = false

vim.pack.add(require("plugins.specs"), pack_opts)

require("plugins.colorscheme")
require("plugins.barbar")
require("plugins.treesitter")
require("plugins.textobjects")
require("plugins.snippets")
require("plugins.completion")
require("plugins.lsp")
require("plugins.formatting")
require("plugins.frontend")
require("plugins.markdown")
require("plugins.search")
require("plugins.replace")
require("plugins.flash")
require("plugins.kulala")
require("plugins.mini_files")
require("plugins.session")
require("plugins.explorers")
require("plugins.outline")
require("plugins.folding")
require("plugins.git")
require("plugins.trouble")
require("plugins.harpoon")
require("plugins.dap")
require("plugins.test")
require("plugins.ui")
require("plugins.smart_splits")
require("plugins.toggleterm")
require("plugins.editing")
